sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - bower_components
install: yarn install
script:
  - npm run build
  - hassio/script/build_hassio
  - cd hass_frontend
  - mkdir hass_frontend
  - mv * hass_frontend
  - cp ../setup.py ./
  - cp ../install_javis_hass.sh ./
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git init
  - git add .
  - git commit -m "update"
  - git remote add origin https://github.com/quanghd96/home-assistant-build.git
dist: trusty
addons:
  sauce_connect: true
  artifacts:
    working_dir: hass_frontend
branches:
  only:
  - master
env:
  global:
    secure: c34c9c15e22bb4b6c74ff08aba38ef3381621aa5
