sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - bower_components
install: yarn install
script:
  - npm run build
  - hassio/script/build_hassio
  - npm run test
deploy:
  provider: script
  script: script/travis_deploy
  'on':
    branch: master
dist: trusty
addons:
  sauce_connect: true

