#!/usr/bin/env bash

# Safe bash settings
# -e            Exit on command fail
# -u            Exit on unset variable
# -o pipefail   Exit if piped command has error code
set -eu -o pipefail
ls
cd hass_frontend
git init
git remote 
git add .
git commit -m "update new version"
git remote add origin https://github.com/quanghd96/home-assistant-build.git
git push -uf origin master